### ISSUE TITLE
Configuring what to parallelize

### ISSUE THREAD

**Issue by mattfysh** [TestArmada/magellan#11]
There are opportunities to split the testing infrastructure between singletons and per-worker components, along with some potential to decide how to distribute the load amongst workers. Some examples:

- boot up only one sauce connect tunnel for the duration of the run
- similarly, only one local selenium server per test runner (I believe selenium servers have "sessions" so you need only create one and then each worker will use a new session)
- dedicate a worker per browser, then run the entire functional test suite in one worker; OR
- one browser + one file per worker (versus one browser + one "it" case)
- the readme suggests manually using npm scripts to perform setup/teardown operations for the entire test run, this is something that could be baked into magellan so that you need only run "magellan" in any scenario

What are your thoughts - does that sound okay?

**Comment by Maciek416** [comment]
Re: Sauce connect tunnels -- we run a tunnel per worker mainly because of encountering major reliability and consistency issues with cramming more than one worker per tunnel. There seem to be some oddball long-standing issues with this on the saucelabs side. This is work some investigation however, because you quickly hit a tunnel-per account limit.

Re: One selenium server per test runner. This is a good idea, however right now, magellan has no real knowledge of what mocha/rowdy or nightwatch are doing selenium-wise within the interior of the worker. As you have observed, this has a drawback of higher resource usage, though it **also** has had the benefit of confining instability to one worker. If individual worker selenium instances crash, we can mostly just keep movin'. That said, it would be interesting if magellan could stand up the local selenium server and then have child workers point at it. On the other hand, it may not be that big of a deal in the grand scheme of things, since the really big scaling happens with remote selenium instances (i.e. SauceLabs).

Re: entire suite vs. chopped-up. I'm excited and supportive of this idea since we could parallelize unit test suites this way across a number of browsers. :)

Re: Baking npm steps into magellan, we're pretty cold on this idea -- magellan should ideally be pretty atomic, and the hope is to fit into a larger `npm` task set as opposed to owning it. Another hope that we've had is to be able to run a given suite without the magellan if desired, especially if mocha (or other supported frameworks) do something better on the tactical day-to-day workflow level (with magellan mainly used for scaling up).

Thanks for your thoughts!

**Comment by mattfysh** [comment]
Those are some really grand design principles, I'm very excited about this project!

I'm playing with a way to configure distribution of load amongst the workers, I'd love to get your eyes on https://github.com/TestArmada/magellan/compare/master...mattfysh:full-mocha-support whenever you get a minute.

This also uses the mocha runtime to extract the tests, having two benefits so far:

1. supports mocha.opts including --require, which I'm using to register coffeescript (as my func specs are written in CS)
2. it allows root-level hooks to be added in files that do not contain the individual test to be run (in the current approach spawning mocha with only the exact file and --grep pattern, adapter.before/after/etc must be either required explicitly or duplicated across all files)

Let me know if you have any feedback on this approach :) thanks!

**Comment by Maciek416** [comment]
Can you PR https://github.com/TestArmada/magellan/compare/master...mattfysh:full-mocha-support ? I want to have a place to chat about it. My initial reaction is **hell yes, thank goodness someone stepped in and did it the non-janky way** :+1: :+1: :+1:

**Comment by mattfysh** [comment]
done :) thanks!

**Comment by mattfysh** [comment]
I'll close this now that we have the PR
