### ISSUE TITLE
feature: json or xunit reporter ?

### ISSUE THREAD

**Issue by chenchaoyi** [TestArmada/magellan#127]
Currently from the CI job, I need to read the console log to find out which tests failed and the cause.

It looks to me a json or xunit report file which tells the basic passed/failed/retry information would be really nice. And it could be used by 3rd party dashboard too.

Any thoughts?

**Comment by Maciek416** [comment]
We definitely want more of this sort of thing. I have some code landing soon which will allow for much richer suite run analysis so that reporters can build a very detailed picture of what happened or track what is happening while a suite run is in progress. I'm not personally familiar with the xunit format. Do you have some examples?

**Comment by archlichking** [comment]
FYI @Maciek416 `http://google.github.io/rich-test-results/xunitxml`, it should be standard among the 3rd party frameworks nowadays, perhaps we can just simply enable a `xunit` reporter and then let the 3rd party framework do the job.
