### ISSUE TITLE
"resolution" config property not working for local runs

### ISSUE THREAD

**Issue by sfaxino** [TestArmada/magellan#165]
Hi there, 

Is there a way to set the browser resolution from the magellan config file for local runs ? 
I added the resolution property as follows but it didn't work for me: 
`"resolution": "480x1024"
`
I also tried to add the "profiles" property but that didn't help either

```
"profiles": {
    "default": [
      { "browser": "chrome", "resolution": "480x1024" }
    ]
  }
```
even the `--resolution=480x1024` switch is not working

Thank you !

**Comment by Maciek416** [comment]
The resolution property doesn't work locally because it's intended to set the resolution of the entire screen of the virtual machine being requested from providers like Saucelabs. If you want to set the size of the browser you'll need to use the browser resize commands in Nightwatch or wd/wdio in the body of your actual tests.

**Comment by sfaxino** [comment]
That makes sense, thank you @Maciek416 !
