### ISSUE TITLE
Decide on convention for env var, vs switch

### ISSUE THREAD

**Issue by geekdave** [TestArmada/magellan#61]

**Comment by Maciek416** [comment]
A few notes for this ticket:

  - For almost all cases, `magellan` consumes environment variables to configure long-running configuration options that don't shift from build to build on a given box (such as auth tokens). There may be a few cases where the lines are blurred (screenshot server location is definitely breaking this rule and should perhaps be an environment variable). I think those blurred-lines need fixes.
  - For workflow options (test to run, `--sauce`, tags, worker count, etc) we use switches. It's worthy of note that `magellan` merges `argv` with options defined in `magellan.json`, so that tedious switches that are always used the same way can be specified in `magellan.json`. This also allows for `profiles` to be defined (larger configuration data structures that would be awkward in environment variable form).
  - This ticket should also have in its scope a task to document a comprehensive index of ALL of magellan's inputs, whether by environment, argv, or `magellan.json` ("stored `argv`", as it were).
