### ISSUE TITLE
Show sauce job result URL in console

### ISSUE THREAD

**Issue by geekdave** [TestArmada/magellan#73]
If a job is linked up with admiral, we show the link to the admiral URL after a suite is complete.  But for jobs not linked with admiral, or if a user wants to jump directly to a sauce result from the console, we should change this:

```
(1 / 1) <-- Worker 1 PASS  loads basic script @IE_8_Windows_2008_Desktop  
```

to this:

```
(1 / 1) <-- Worker 1 PASS  loads basic script @IE_8_Windows_2008_Desktop  https://saucelabs.com/tests/1234567890
```

**Comment by Maciek416** [comment]
I also wish there was some way of obtaining the selenium session id **at the start**, so that someone can immediately jump into sauce and follow along on a test they care about.

Technically-speaking, this is super hard or maybe impossible without interprocess communication + forcing users to use helper libraries, but also, we show a start message as soon as we `spawn()` and the selenium session in wd, webdriver, and nightwatch happens much much later.

I wish there was a way to warm up a selenium session with magellan itself and do ```
anyframework --selenium_session_id=adbe678fde
```

Then we could do a lot of job result integration from "cradle to grave".

**Comment by Maciek416** [comment]
This is now easier than it previously was.
